package main;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.io.File;
import java.sql.*;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import javax.swing.JOptionPane;
import koneksi.koneksi;


/**
 * @author Raynold
 */
public class Daftar extends javax.swing.JFrame {
    Statement st;
    ResultSet rs;
    koneksi koneksi;
                
    public Daftar() { 
        koneksi = new koneksi();
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Form Register karyawan");
        IDOtomatis();
        level();
    }
        
    private void IDOtomatis() {
        try {
            st=koneksi.con2.createStatement();
            String sql="SELECT * FROM tbl_karyawan order by ID_KARYAWAN desc";
            rs=st.executeQuery(sql);
            if(rs.next()) {
                String ID=rs.getString("ID_KARYAWAN").substring(4);
                String NO = "" + (Integer.parseInt(ID) + 1);
                String Nol = "";
                if(NO.length()==1) {
                    Nol="000";
                } else if(NO.length()==2) {
                    Nol="00";
                }
                IIdUser.setText("USER" + Nol + NO);
            } else {
                IIdUser.setText("USER0001");
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    //load Data Level Daroi Tabel Level ke ComboBox Level
    public void level() {
        try {
            st = koneksi.con2.createStatement();
            String query = "SELECT * FROM tbl_level";
            rs = st.executeQuery(query);
            while (rs.next()) {
                CLevel.addItem(rs.getString("LEVEL"));
            }
            rs.close();
        } catch (SQLException e)  { }
    }

    public void input_data() {
        String jk="";
        try {
            //Mengambil Data Jenis Kelamin
            if(JkL.isSelected()) {
                jk = JkL.getText();
            } else {
                jk = JkP.getText();
            }

            //Mengambil ComboBox
            st=koneksi.con2.createStatement();
            String query = "SELECT ID_LEVEL FROM tbl_level WHERE LEVEL='"+CLevel.getSelectedItem()+"'";
            rs = st.executeQuery(query);
            String id = "";
            if(rs.next()) {
                id = rs.getString("ID_LEVEL");
            }
            //Query Input ke Tabel USer
            String sql="INSERT INTO tbl_karyawan values('"+IIdUser.getText()
            +"','"+id
            +"','"+INama.getText()
            +"','"+jk
            +"','"+INope.getText()
            +"','"+IUsername.getText()
            +"','"+IPassword.getText()
            +"')";
            st.execute(sql);
            JOptionPane.showMessageDialog(null, "Data Barang Berhasil Dimasukan");
        } catch(SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        IIdUser = new javax.swing.JTextField();
        CLevel = new javax.swing.JComboBox<>();
        INama = new javax.swing.JTextField();
        JkL = new javax.swing.JRadioButton();
        JkP = new javax.swing.JRadioButton();
        INope = new javax.swing.JTextField();
        IUsername = new javax.swing.JTextField();
        BSimpan = new javax.swing.JButton();
        BHapus = new javax.swing.JButton();
        IPassword = new javax.swing.JPasswordField();
        BKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("FORM INPUT USER");

        jLabel2.setText("ID USER");

        jLabel3.setText("LEVEL");

        jLabel4.setText("NAMA USER");

        jLabel5.setText("JENIS KELAMIN");

        jLabel6.setText("NO HP");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("USERNAME");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("PASSWORD");

        IIdUser.setEditable(false);

        CLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--" }));

        buttonGroup1.add(JkL);
        JkL.setText("L");

        buttonGroup1.add(JkP);
        JkP.setText("P");

        BSimpan.setText("SIMPAN");
        BSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSimpanActionPerformed(evt);
            }
        });

        BHapus.setText("HAPUS");
        BHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHapusActionPerformed(evt);
            }
        });

        BKembali.setText("Kembali");
        BKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(BKembali))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(CLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(JkL)
                                    .addGap(18, 18, 18)
                                    .addComponent(JkP))
                                .addComponent(IIdUser, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(22, 22, 22)
                                    .addComponent(BSimpan)
                                    .addGap(34, 34, 34)
                                    .addComponent(BHapus))
                                .addComponent(INama)
                                .addComponent(IUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(INope, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(IPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel1)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(IIdUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(INama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(JkL)
                    .addComponent(JkP))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(INope, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(IUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(IPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BSimpan)
                    .addComponent(BHapus)
                    .addComponent(BKembali))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSimpanActionPerformed
        // TODO add your handling code here:
        String alert = "";
        int numAlert = 0;
        if (IIdUser.getText().equals("")) {
            alert = alert+"&koma; Id User";
            numAlert = numAlert+1;
        }
        if (CLevel.getSelectedItem().equals("--Select--")) {
            alert = alert+"&koma; Level";
            numAlert = numAlert+1;
        }
        if (INama.getText().equals("")) {
            alert = alert+"&koma; Nama User";
            numAlert = numAlert+1;
        }
        if (!JkL.isSelected() && !JkP.isSelected()) {
            alert = alert+"&koma; Jenis Kelamin";
            numAlert = numAlert+1;
        }
        if (INope.getText().equals("")) {
            alert = alert+"&koma; Nomor Hp";
            numAlert = numAlert+1;
        }
        if (IUsername.getText().equals("")) {
            alert = alert+"&koma; Username";
            numAlert = numAlert+1;
        }
        if (String.valueOf(IPassword.getPassword()).equals("")) {
            alert = alert+"&koma; Password";
            numAlert = numAlert+1;
        }
        if (alert != "") {
            if (numAlert > 1) {
                alert=alert.replace("&koma;",",");
                alert=alert.replaceFirst(",", "");
            } else {
                alert=alert.replace("&koma;","");
            }
            JOptionPane.showMessageDialog(null, alert+" Belum diisi!!");
        } else {
            int Confirm = JOptionPane.showOptionDialog(this, "Ingin simpan data?", "Konfirmasi", 
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
            if(Confirm == JOptionPane.YES_OPTION){
                input_data();
                login login = new login();
                this.setVisible(false);
                JOptionPane.showMessageDialog(null, "Akun anda Sudah didaftarkan !!");
                login.setVisible(true);
            }
        }
    }//GEN-LAST:event_BSimpanActionPerformed

    private void BHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHapusActionPerformed
        // TODO add your handling code here:
        CLevel.setSelectedIndex(0);
        INama.setText("");
        JkL.setSelected(false);
        JkP.setSelected(false);
        INope.setText("");
        IUsername.setText("");
        IPassword.setText("");
    }//GEN-LAST:event_BHapusActionPerformed

    private void BKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BKembaliActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new login().setVisible(true);
    }//GEN-LAST:event_BKembaliActionPerformed
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Daftar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BHapus;
    private javax.swing.JButton BKembali;
    private javax.swing.JButton BSimpan;
    private javax.swing.JComboBox<String> CLevel;
    private javax.swing.JTextField IIdUser;
    private javax.swing.JTextField INama;
    private javax.swing.JTextField INope;
    private javax.swing.JPasswordField IPassword;
    private javax.swing.JTextField IUsername;
    private javax.swing.JRadioButton JkL;
    private javax.swing.JRadioButton JkP;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
